# -Wall tells the compiler, cc, to report all warnings (which, in a sick twist of fate, isn't actually all the warnings possible; -Wextra prints more warnings but still not all - see `man gcc` for more about these flags if interested)
# -g flag to get debugging
# Macros are defined as = pairs.
CFLAGS=-Wall -g

# The general syntax of a Makefile target rule is −
# target [target...] : [dependent ....]
	# [ command ...]
# In the above code, the arguments in brackets are optional and ellipsis means one or more. Here, note that the tab to preface each command is required.
all: ex4

clean:
	rm -f ex4
